Repository simonihmig/tracked-redux, pull requests merged in 2022-02, with the labels that each got.

#114 Migrate proxy.js to TS, use strict types
  package.json
  src/-private/create-store.ts
  src/-private/devtools.js
  src/-private/proxy.js
  src/-private/proxy.ts
  src/-private/tracking.ts
  src/index.ts
  tsconfig.json
Labels: internal

#121 Use ember-tracked-storage-polyfill
  packages/tracked-redux/package.json
  packages/tracked-redux/src/-private/tracking.ts
  yarn.lock
Labels: enhancement

#122 Setup release-it
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#123 Defend against use in cycles
  packages/tracked-redux/src/-private/tracking.ts
Labels: bug
